config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :pictures, exept: :show do
    # collection do
      post :confirm
    # end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # >>>>>>ここから
    if user && user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :manage, :all           # allow superadmins to do anything
    end
    # =====ここまでを追記
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
    validates :title, presence: true
    validates :image, presence: true
    belongs_to :user
    mount_uploader :image, ToukouimageUploader #deviseの設定配下に追記
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :confirmable
  mount_uploader :avatar, AvatarUploader #deviseの設定配下に追記
  has_many :pictures

  def self.create_unique_string
    SecureRandom.uuid
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(email: auth.info.email)

    unless user
      user = User.new(
          name:     auth.extra.raw_info.name,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          image_url:   auth.info.image,
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end
  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end
  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_actionで下で定義したメソッドを実行
  before_action :configure_permitted_parameters, if: :devise_controller?

  #変数PERMISSIBLE_ATTRIBUTESに配列[:name]を代入
  PERMISSIBLE_ATTRIBUTES = %i(name avatar avatar_cache)

  protected

    #deviseのストロングパラメーターにカラム追加するメソッドを定義
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
    end
####################
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_picture, only: [:edit, :update, :destroy]
  def index
    @pictures =Picture.all
  end

  def new
    @picture = Picture.new
  end

  def create
     @picture = Picture.new(pictures_params)
     @picture.user_id = current_user.id
     if @picture.save
       redirect_to pictures_path(@picture), notice: "投稿完了しました！"
       NoticeMailer.sendmail_picture(@picture).deliver
     else
       render 'new'
     end
  end
  def edit
  end

  def update
    if @picture.update(pictures_params)
      redirect_to pictures_path, notice: "投稿を更新しました！"
    else
      render action: 'edit'
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice: "投稿を削除しました！"
  end

private
  def pictures_params
    params.require(:picture).permit(:title,:image,:content)
  end
  def set_picture
    @picture = Picture.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
     @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

     if @user.persisted?
       set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
       sign_in_and_redirect @user, event: :authentication
     else
       session["devise.facebook_data"] = request.env["omniauth.auth"]
       redirect_to new_user_registration_url
     end
  end
  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def profile_img(user)
    return image_tag(user.avatar, alt: user.name) if user.avatar?

    unless user.provider.blank?
      img_url = user.image_url
    else
      img_url = 'no_image.png'
    end
    image_tag(img_url, alt: user.name)
  end
end

module ActionView
  module Helpers
    module FormHelper
      def error_messages!(object_name, options = {})
        resource = self.instance_variable_get("@#{object_name}")
        return '' if !resource || resource.errors.empty?

        messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

        html = <<-HTML
          <div class="alert alert-danger">
            <ul>#{messages}</ul>
          </div>
        HTML

        html.html_safe
      end

      def error_css(object_name, method, options = {})
        resource = self.instance_variable_get("@#{object_name}")
        return '' if resource.errors.empty?

        resource.errors.include?(method) ? 'has-error' : ''
      end
    end

    class FormBuilder
      def error_messages!(options = {})
        @template.error_messages!(@object_name, options.merge(object: @object))
      end

      def error_css(method, options = {})
        @template.error_css(@object_name, method, options.merge(object: @object))
      end
    end
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Instamodoki</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <header>
            <nav class="navbar navbar-default">
                <h1 class="hdrh1">
                    <a href="" class="navbar-brand">
                        インスタもどき
                    </a>
                </h1>
                <ul class="nav navbar-nav right">
                    <% if user_signed_in? %>
                    <li><%= link_to 'マイページ', edit_user_registration_path %></li>
                    <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
                <% else %>
                    <li>
                        <%= link_to 'ログイン', new_user_session_path %>
                    </li>
                    <li>
                        <%= link_to 'サインイン', new_user_registration_path %>
                    </li>
                    <% end %>
                </ul>
            </nav>
        </header>
        <p><%= notice %></p>
        <div class="col-md-8 col-md-offset-2 col-sm-12 mb200">
            <%= yield %>
        </div>
    </body>
</html>

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <%= f.error_messages! %>
  <%= f.label :タイトル %><br>
  <%= f.text_field :title %>
  <%= f.file_field :image %><br>
  <%= f.hidden_field :image_cache %>
  <%= f.label :記事内容 %><br>
  <%= f.text_field :content %><br>
  <%= f.submit %>
<% end %>
<%= link_to "一覧にもどる", pictures_path %>

app/views/pictures/edit.html.erb
  <%= render 'form' %>

app/views/pictures/index.html.erb
<h2 class="kijih2">記事一覧</h2>

    <% @pictures.each do |picture| %>
    <article class="card">
      <div class="card-header">
            <% if picture.user.avatar.model.avatar.present? %>
            <%= image_tag picture.user.avatar, size: "100x100",alt: "avatar" %>
            <% elsif picture.user.image_url %>
            <%= image_tag picture.user.image_url, size: "100x100",alt: "avatar" %>
            <% else %>
            <%= image_tag "no_image.png", size: "100x100",alt: "no_image" %>
            <% end %>

        <div class="title">
            <h1>
              タイトル：<%= picture.title %>
            </h1>
              <p><%= picture.user.name %>さんが投稿しました&nbsp;&nbsp;&nbsp;ID:&nbsp;&nbsp;<%= picture.user.id %></p>

        </div>
      </div>
      <div class="card-block">
        <P><img src="<%= picture.image %>"></P>
      </div>
      <div class="card-footer">
          <p><%= picture.content %></p>
      </div>
      <%= link_to  "投稿を編集する", edit_picture_path(picture.id) %><br>
      <%= link_to  "投稿を削除する", picture_path(picture),method: :delete %>
    </article>
    <% end %>

<br>
<hr>
<%= link_to "新規投稿" ,new_picture_path %>

app/views/pictures/new.html.erb
  <%= render 'form' %>

app/views/pictures/show.html.erb
<h1>Blogs#show</h1>
<p>Find me in app/views/blogs/show.html.erb</p>

app/views/top/index.html.erb
<%= link_to "ブログを作成する" ,new_blog_path %>